name: Frontend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build frontend app
      run: npm run build
      working-directory: frontend

    - name: Run frontend tests
      run: npm test
      working-directory: frontend
