name: Update campaigns status

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'

jobs:
  cron-job:
    runs-on: ubuntu-latest

    steps:
    - name: Send PATCH request to update campaigns status
      run: |
        curl -X PATCH ${{ secrets.API_URL }}/campaigns/update-status
